version: '3.5'

services:
  streama:
    image: quay.io/kalkspace/stroma-streama:main
    volumes:
      - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie
    user: "1000:1000"
    restart: always

  ssh:
    image: jnovack/autossh
    environment:
      SSH_REMOTE_USER: pi
      SSH_REMOTE_HOST: k3s.kalk.space
      SSH_REMOTE_PORT: 30022
      SSH_TUNNEL_PORT: 80
      SSH_BIND_IP: marcus
      SSH_TARGET_HOST: streama
      SSH_TARGET_PORT: 8080
    restart: always
    volumes:
      - /etc/autossh/id_rsa:/id_rsa
    dns:
      - 8.8.8.8
      - 4.2.2.4
