version: '3.5'

services:
  streama:
    image: quay.io/kalkspace/stroma-streama:sha-037df3e
    devices:
      - "todo sound device"

  ssh:
    image: jnovack/autossh
    environment:
      SSH_REMOTE_USER: pi
      SSH_REMOTE_HOST: marcus
      SSH_REMOTE_PORT: 80
      SSH_BIND_IP: 0.0.0.0
      SSH_TARGET_HOST: streama
      SSH_TARGET_PORT: 8080
    restart: always
    volumes:
      - /etc/autossh/id_rsa:/id_rsa
