- name: Configure the streamer
  hosts: all
  tasks:
    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: /etc/autossh/id_rsa

    - name: Install dependencies
      package:
        name:
          - docker.io
          - docker-compose
          - python3-docker

    - name: Apply docker-compose services
      community.docker.docker_compose:
        project_name: stroma
        definition: "{{ lookup('file', 'docker-compose.yml') | from_yaml }}"
